# Generated by Django 3.2.3 on 2021-06-06 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
